/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef __PLUGINEDITOR_H_AE26B735__
#define __PLUGINEDITOR_H_AE26B735__

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"
#include "MainPanel.h"


//==============================================================================
/**
*/
class ConvolutionAudioProcessorEditor  : public AudioProcessorEditor
{
public:
    ConvolutionAudioProcessorEditor (ConvolutionAudioProcessor* ownerFilter);
    ~ConvolutionAudioProcessorEditor();

    //==============================================================================
    // This is just a standard Juce paint method...
    void paint (Graphics& g);
private:
	MainPanel* panel;
};


#endif  // __PLUGINEDITOR_H_AE26B735__
